### ISSUE TITLE
unable to run after git pull today

### ISSUE THREAD

**Issue by vincentcsm** [PokemonGoF/PokemonGo-Bot-Desktop#149]
_Issue without proper information won't be answered_
### Expected Behavior

i did git pull and npm install today
after that npm start show below error
### Actual Behavior

bash-3.2# npm start

> PokemonGoBot@0.0.1-alpha start /Users/Vincent.Chau/Desktop/newpkmongo/PokemonGo-Bot-Desktop
> gulp run

/Users/Vincent.Chau/Desktop/newpkmongo/PokemonGo-Bot-Desktop/gulpfile.js:44
            let parsed = data.toString().split('\n');
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/Users/Vincent.Chau/Desktop/newpkmongo/PokemonGo-Bot-Desktop/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/Vincent.Chau/Desktop/newpkmongo/PokemonGo-Bot-Desktop/node_modules/liftoff/index.js:198:16)
    at module.exports (/Users/Vincent.Chau/Desktop/newpkmongo/PokemonGo-Bot-Desktop/node_modules/flagged-respawn/index.js:17:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha start: `gulp run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'gulp run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Vincent.Chau/Desktop/newpkmongo/PokemonGo-Bot-Desktop/build/gofbot/npm-debug.log
### Information
- OS OSX 10.11.6
- Git commit b46158c916d0657770214bd88968710eadfc1139
- App's logs

**Comment by vincentcsm** [comment]
i did exactly same step with 0.0.2 Release
but it works with 0.0.2

**Comment by Outpox** [comment]
It seems like you're using node v5.6.0 and npm 3.6.0  
Could you please update them? (Note that updating nodejs will update npm as well).

**Comment by vincentcsm** [comment]
@Outpox thanks problem solved after brew upgrade node
but npm start get another problem 

![screen shot 2016-08-12 at 4 26 10 pm](https://cloud.githubusercontent.com/assets/20834721/17616897/82c4b9e4-60a9-11e6-82c2-880e01fa57e8.png)
and then process keep running 
![screen shot 2016-08-12 at 4 26 57 pm](https://cloud.githubusercontent.com/assets/20834721/17616911/9f004498-60a9-11e6-90a5-31c5de706148.png)

**Comment by Outpox** [comment]
There was an update 32mn ago, did you pulled it?

**Comment by vincentcsm** [comment]
@Outpox yep i did
current build
- Git commit d7cb7df27516b588252a767260176f92586489fa

**Comment by vincentcsm** [comment]
i got warning when use pip install -r requirement.txt

Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/keyphact/pgoapi.git (to a2755eb42dfe49e359798d2f4defefc97fb8163d) to ./src/pgoapi
  Could not find a tag or branch 'a2755eb42dfe49e359798d2f4defefc97fb8163d', assuming commit.

**Comment by Outpox** [comment]
You can ignore this warning.

**Comment by lkwjohn** [comment]
facing the same issue also:

Unable to find Electron app at /Users/john/PokemonGo-Bot-Desktop/build

Cannot find module '/Users/john/PokemonGo-Bot-Desktop/build'
