### PR TITLE
Fixing previous code refactor

### LINKED ISSUE #127: Cannot find module 'jquery', map frozen and always showing 'Loading...' on account info
### Expected Behavior

Account info and map updated must be updated.

captura de tela 2016-08-11 as 11 37 34
captura de tela 2016-08-11 as 11 37 32
captura de tela 2016-08-11 as 11 37 45
### Actual Behavior

Account info is always showing 'Loading...'
Map is frozen.
### Steps to Reproduce

Install normally, npm start and log in.  
### Information
- macOS
- PikaBot 0.0.1-alpha

### PR DESCRIPTION
**Pull request by kdemoya**
This PR fixes #127 and #128. Error was introduced in #125 which were missing a few things and was not rebased before merging.

### CODE REVIEW

**Comment by kdemoya** [comment]
Closing in favor of #135.
